jsachievements-web/Atanu/laravelVue/shopping-cart/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
//Route::get('/products', 'ProductListController@index')->name('products.index');
Route::resource('products','ProductListController');
Route::resource('addNew','AddNewProductController');

jsachievements-web/Atanu/laravelVue/shopping-cart/app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = [
        'name',
        'price', 
        'desc',
        'image',
        'created_user_id',
        'updated_user_id',
        'product_category_id'
    ];

   	public function users(){
        return $this->belongsTo('app/User');
    }

    public function product_category(){
        return $this->belongsTo('app/ProductCategory');
    }

    /*protected $hidden = [
        'product_category_id'
    ];*/
}

jsachievements-web/Atanu/laravelVue/shopping-cart/resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-9 col-lg-9 col-sm-9">
  <div class="panel panel-default">
    <div class="panel-heading">Add New Product</div>
    <div class="panel-body">
      <form method="post" action="{{route('products.store')}}" enctype="multipart/form-data">
      {{ csrf_field() }}  
        <input type="hidden" name="userId" id="userId" value="{{Auth::id()}}">
        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" class="form-control" id="pname" placeholder="Enter Product name" name="pname">
        </div>

        <div class="form-group">
          <label for="category">Category:</label>
          <select class="form-control" name="pcategory" id="pcategory">
            <option value="">Please Select...</option>
            <option value="2">Mobile</option>
            <option value="3">Laptop</option>
          </select>
        </div>

        <div class="form-group">
          <label for="price">Price:</label>
          <input type="text" class="form-control" id="pprice" placeholder="Enter Product Price" name="pprice">
        </div>

        <div class="form-group">
          <label for="Image">Select Image:</label>
          <input type="file" class="form-control" id="pimage" name="pimage">
        </div>

        <div class="form-group">
          <label for="desc">Description:</label>
          <textarea class="form-control" id="pdesc" placeholder="Enter Product Description" name="pdesc"></textarea>
        </div>

        <!--<div class="checkbox">
          <label><input type="checkbox" name="remember"> Remember me</label>
        </div>-->

        <button type="submit" class="btn btn-primary">Add</button>
      </form>
    </div>
  </div>
</div> 
@endsection

jsachievements-web/Atanu/laravelVue/shopping-cart/resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-9 col-lg-9 col-sm-9">
  <div class="panel panel-default">
    <div class="panel-heading">Edit Details</div>
    <div class="panel-body">
      <form method="post" action="{{route('products.update',[$product->id])}}">
      {{ csrf_field() }}
        <input type="hidden" name="_method" value="put">
        <div class="form-group">
          <label for="name">Name:</label>
          <input type="text" class="form-control" id="pname" placeholder="Enter Product name" name="pname" value="{{$product->name}}">
        </div>

        <div class="form-group">
          <label for="price">Price:</label>
          <input type="text" class="form-control" id="pprice" placeholder="Enter Product Price" name="pprice" value="{{$product->price}}">
        </div>

        <div class="form-group">
          <label for="Image">Select Image:</label>
          <input type="file" class="form-control" id="pimage" placeholder="Select Product Image" name="pimage" value="{{$product->image}}">
        </div>

        <div class="form-group">
          <label for="desc">Description:</label>
          <textarea class="form-control" id="pdesc" placeholder="Enter Product Description" name="pdesc">{{$product->desc}}</textarea>
        </div>

        <!--<div class="checkbox">
          <label><input type="checkbox" name="remember"> Remember me</label>
        </div>-->

        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
  </div>
</div> 
@endsection

jsachievements-web/Atanu/laravelVue/shopping-cart/resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-9 col-lg-9">
	<div class="panel panel-primary"> 
		<div class="panel-heading">Product List</div> 
		<table class="table"> 
			<thead> 
				<tr> 
					<th>#</th> 
					<th class="text-center">Product Name</th> 
					<th class="text-center">Price</th>
					<th class="text-center">Permission</th>
				</tr> 
			</thead> 
			<tbody> 
				@foreach($products as $indexKey =>$product)
					<tr> 
						<th scope="row">{{++$indexKey}}</th> 
						<td class="text-center">{{$product->name}}</td> 
						<td class="text-center">{{$product->price}}</td> 
						<td class="text-center">
							<a href="/products/{{$product->id}}"><button class="btn btn-success">View</button></a>
							<a href="/products/{{$product->id}}/edit"><button class="btn btn-primary">Edit</button></a>

							<button class="btn btn-danger"
								onclick="
									var result=confirm('Are you sure you wish to delete this Product?');
									if(result){
										event.preventDefault();
										document.getElementById('delete-form-{{$indexKey}}').submit();
									}
								">
								Delete
							</button>

							<form id="delete-form-{{$indexKey}}" action="{{ route('products.destroy', [$product->id]) }}"method="POST" style="display: none;">
								<input type="hidden" name="_method" value="delete">
								{{ csrf_field() }}
							</form>
							<!-- <span class="glyphicon glyphicon-trash"></span>-->
	        			</td> 
					</tr> 
				@endforeach
			</tbody> 
		</table> 
	</div>
</div>

@endsection

jsachievements-web/Atanu/laravelVue/shopping-cart/resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')

<div class="col-md-9 col-lg-9">
	<div class="panel panel-primary"> 
		<div class="panel-heading">
			Product Details 
			<a href="/products/">
				<button class="btn btn-danger pull-right btn-sm">Close</button>
			</a>
		</div> 
		<table class="table"> 
			<thead> 
				<tr> 
					<th class="text-center">Name</th> 
					<th class="text-center">Description</th>
				</tr> 
			</thead> 
			<tbody> 
				<tr> 
					<td class="text-center"> Name </td>
					<td class="text-center">{{$product->name}}</td> 
				</tr> 
				<tr> 
					<td class="text-center"> Price </td>
					<td class="text-center">{{$product->price}}</td> 
				</tr> 
				<tr> 
					<td class="text-center"> Image </td>
					<td class="text-center">
						<img src="{{ asset('images/' . $product->image) }}" style="width: 200px" >
					</td> 
				</tr> 
				<tr> 
					<td class="text-center"> Description </td>
					<td class="text-center">{{$product->desc}}</td> 
				</tr> 
			</tbody> 
		</table> 
	</div>
</div>

@endsection